package processor

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/grain-framework/grain/pkg/annotation/registry"
)

// APIDocGenerator API文档生成器
type APIDocGenerator struct {
	generator *Generator
	outputDir string
}

// NewAPIDocGenerator 创建新的API文档生成器
func NewAPIDocGenerator(generator *Generator, outputDir string) *APIDocGenerator {
	return &APIDocGenerator{
		generator: generator,
		outputDir: outputDir,
	}
}

// GenerateDocs 生成API文档
func (adg *APIDocGenerator) GenerateDocs() error {
	// 1. 解析所有注解
	annotations := adg.generator.registry.GetAll()

	// 2. 生成Markdown文档
	if err := adg.generateMarkdownDocs(annotations); err != nil {
		return fmt.Errorf("failed to generate markdown docs: %w", err)
	}

	// 3. 生成HTML文档
	if err := adg.generateHTMLDocs(annotations); err != nil {
		return fmt.Errorf("failed to generate HTML docs: %w", err)
	}

	// 4. 生成OpenAPI规范
	if err := adg.generateOpenAPISpec(annotations); err != nil {
		return fmt.Errorf("failed to generate OpenAPI spec: %w", err)
	}

	return nil
}

// generateMarkdownDocs 生成Markdown文档
func (adg *APIDocGenerator) generateMarkdownDocs(annotations []registry.Annotation) error {
	docPath := filepath.Join(adg.outputDir, "API.md")

	content := adg.buildMarkdownContent(annotations)

	if err := os.WriteFile(docPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write markdown file: %w", err)
	}

	return nil
}

// generateHTMLDocs 生成HTML文档
func (adg *APIDocGenerator) generateHTMLDocs(annotations []registry.Annotation) error {
	docPath := filepath.Join(adg.outputDir, "API.html")

	content := adg.buildHTMLContent(annotations)

	if err := os.WriteFile(docPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write HTML file: %w", err)
	}

	return nil
}

// generateOpenAPISpec 生成OpenAPI规范
func (adg *APIDocGenerator) generateOpenAPISpec(annotations []registry.Annotation) error {
	docPath := filepath.Join(adg.outputDir, "openapi.yaml")

	content := adg.buildOpenAPIContent(annotations)

	if err := os.WriteFile(docPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write OpenAPI file: %w", err)
	}

	return nil
}

// buildMarkdownContent 构建Markdown内容
func (adg *APIDocGenerator) buildMarkdownContent(annotations []registry.Annotation) string {
	var content strings.Builder

	content.WriteString("# gRain Framework API Documentation\n\n")
	content.WriteString("## Overview\n\n")
	content.WriteString("This document describes the API endpoints and services generated by the gRain framework.\n\n")

	// 按类型分组注解
	annotationsByType := make(map[string][]registry.Annotation)
	for _, annotation := range annotations {
		annoType := annotation.GetType().String()
		annotationsByType[annoType] = append(annotationsByType[annoType], annotation)
	}

	// 生成每种类型的文档
	for annoType, annoList := range annotationsByType {
		content.WriteString(fmt.Sprintf("## %s\n\n", strings.Title(annoType)))

		for _, annotation := range annoList {
			content.WriteString(fmt.Sprintf("### %s\n\n", annotation.GetTargetName()))
			content.WriteString(fmt.Sprintf("- **Type**: %s\n", annotation.GetType()))
			content.WriteString(fmt.Sprintf("- **Target**: %s\n", annotation.GetTargetType()))
			content.WriteString(fmt.Sprintf("- **Name**: %s\n\n", annotation.GetTargetName()))
		}
	}

	return content.String()
}

// buildHTMLContent 构建HTML内容
func (adg *APIDocGenerator) buildHTMLContent(annotations []registry.Annotation) string {
	var content strings.Builder

	content.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>gRain Framework API Documentation</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .endpoint { border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px; }
        .method { font-weight: bold; color: #007bff; }
        .path { font-family: monospace; background: #f8f9fa; padding: 5px; }
    </style>
</head>
<body>
    <h1>gRain Framework API Documentation</h1>
    <div id="content">`)

	// 按类型分组注解
	annotationsByType := make(map[string][]registry.Annotation)
	for _, annotation := range annotations {
		annoType := annotation.GetType().String()
		annotationsByType[annoType] = append(annotationsByType[annoType], annotation)
	}

	// 生成每种类型的文档
	for annoType, annoList := range annotationsByType {
		content.WriteString(fmt.Sprintf("<h2>%s</h2>", strings.Title(annoType)))

		for _, annotation := range annoList {
			content.WriteString(fmt.Sprintf(`
            <div class="endpoint">
                <h3>%s</h3>
                <p><strong>Type:</strong> %s</p>
                <p><strong>Target:</strong> %s</p>
                <p><strong>Name:</strong> %s</p>
            </div>`,
				annotation.GetTargetName(),
				annotation.GetType(),
				annotation.GetTargetType(),
				annotation.GetTargetName()))
		}
	}

	content.WriteString(`
    </div>
</body>
</html>`)

	return content.String()
}

// buildOpenAPIContent 构建OpenAPI内容
func (adg *APIDocGenerator) buildOpenAPIContent(annotations []registry.Annotation) string {
	var content strings.Builder

	content.WriteString(`openapi: 3.0.0
info:
  title: gRain Framework API
  version: 1.0.0
  description: API generated by gRain framework
paths:`)

	// 按类型分组注解
	annotationsByType := make(map[string][]registry.Annotation)
	for _, annotation := range annotations {
		annoType := annotation.GetType().String()
		annotationsByType[annoType] = append(annotationsByType[annoType], annotation)
	}

	// 生成路由相关的OpenAPI规范
	if routes, exists := annotationsByType["route"]; exists {
		for _, route := range routes {
			// 这里可以根据路由注解的属性生成具体的OpenAPI路径
			content.WriteString(`
  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: Successful response`)
		}
	}

	return content.String()
}
